import puppeteer from 'puppeteer';

export const generatePdfFromHtml = async (html: string): Promise<Buffer> => {
  let browser;
  try {
    // Launch browser with optimized settings for server environment
    browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--no-first-run',
        '--no-zygote',
        '--single-process',
        '--disable-gpu'
      ]
    });

    const page = await browser.newPage();

    // Set content and wait for it to load
    await page.setContent(html, { waitUntil: 'networkidle0' });

    // Generate PDF
    const pdfArray = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '20mm',
        right: '20mm',
        bottom: '20mm',
        left: '20mm'
      }
    });

    return Buffer.from(pdfArray);
  } catch (error) {
    console.error('PDF generation error:', error);
    throw new Error('Failed to generate PDF');
  } finally {
    if (browser) {
      await browser.close();
    }
  }
};

export const createSampleReportHtml = (): string => {
  const timestamp = new Date().toLocaleString();

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>EstateNet Sample Report</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 20px;
          color: #333;
        }
        .header {
          text-align: center;
          border-bottom: 2px solid #007bff;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .header h1 {
          color: #007bff;
          margin: 0;
        }
        .timestamp {
          text-align: center;
          color: #666;
          margin-bottom: 30px;
        }
        .section {
          margin-bottom: 30px;
        }
        .section h2 {
          color: #007bff;
          border-bottom: 1px solid #ddd;
          padding-bottom: 10px;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 15px;
        }
        th, td {
          border: 1px solid #ddd;
          padding: 12px;
          text-align: left;
        }
        th {
          background-color: #f8f9fa;
          font-weight: bold;
        }
        tr:nth-child(even) {
          background-color: #f8f9fa;
        }
        .footer {
          margin-top: 50px;
          text-align: center;
          color: #666;
          font-size: 12px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>EstateNet Sample Report</h1>
      </div>
      
      <div class="timestamp">
        Generated on: ${timestamp}
      </div>
      
      <div class="section">
        <h2>Property Summary</h2>
        <table>
          <thead>
            <tr>
              <th>Property Name</th>
              <th>Location</th>
              <th>Total Units</th>
              <th>Occupied Units</th>
              <th>Occupancy Rate</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Sunrise Apartments</td>
              <td>Kampala, Nakasero</td>
              <td>5</td>
              <td>4</td>
              <td>80%</td>
            </tr>
            <tr>
              <td>Garden View Estate</td>
              <td>Kampala, Kololo</td>
              <td>3</td>
              <td>2</td>
              <td>67%</td>
            </tr>
          </tbody>
        </table>
      </div>
      
      <div class="section">
        <h2>Financial Overview</h2>
        <table>
          <thead>
            <tr>
              <th>Metric</th>
              <th>Amount (UGX)</th>
              <th>Change</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Total Monthly Rent</td>
              <td>8,600,000</td>
              <td>+5.2%</td>
            </tr>
            <tr>
              <td>Outstanding Rent</td>
              <td>2,400,000</td>
              <td>-12.1%</td>
            </tr>
            <tr>
              <td>Monthly Expenses</td>
              <td>4,300,000</td>
              <td>+2.8%</td>
            </tr>
            <tr>
              <td>Net Income</td>
              <td>4,300,000</td>
              <td>+7.9%</td>
            </tr>
          </tbody>
        </table>
      </div>
      
      <div class="footer">
        <p>This is a sample report generated by EstateNet Property Management System</p>
        <p>For inquiries, contact: support@estatenet.ug | +256 414 123 456</p>
      </div>
    </body>
    </html>
  `;
};
